### ISSUE TITLE
config is not loaded from $HOME/.config/shell-craft/config.json due to improper usage of ~ in path

### ISSUE THREAD

**Issue by BLuFeNiX** [JohnnyIrvin/shell-craft#103]
https://github.com/JohnnyIrvin/shell-craft/blob/26a7af762f5eb905105b55d6c4b870946a2d577f/shell_craft/cli/main.py#L43

Needs to use `os.path.expanduser`

**Comment by JohnnyIrvin** [comment]
Fixed in https://github.com/JohnnyIrvin/shell-craft/releases/tag/v1.1.1
