### ISSUE TITLE
shell-craft not added to $PATH

### ISSUE THREAD

**Issue by joelfourhman** [JohnnyIrvin/shell-craft#37]
pip install openai-shell-craft succeeds, but is not added to $PATH

**Comment by SheepReaper** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/5705509/227408374-94bc4e7d-7f18-4adb-af49-b1a6289d011c.png">

Add your python scripts directory to either your system PATH or user PATH. You may need to restart your terminal or system depending on which you modify.
