### ISSUE TITLE
Interactive Mode

### ISSUE THREAD

**Issue by JohnnyIrvin** [JohnnyIrvin/shell-craft#58]
Allow users to have a continuing conversation with shell-craft

**Is your feature request related to a problem? Please describe.**
Currently, all prompts in shell-craft are one off prompts, so users are unable to continue the conversation beyond the initial prompt. This can be frustrating for users who want to continue the same prompt.

**Describe the solution you'd like**
I would like to see an interactive mode added to shell-craft, using `--interactive`, where users can continue the conversation beyond the initial prompt. This would allow users to have a more natural and flowing prompt experience.

**Describe alternatives you've considered**
One potential alternative would be to have a large number of prompts available so that users can switch between different topics and continue a conversation that way. Which, is what we are currently doing. However, this is resulting in a very large number of prompts, which may be impractical.

It may be worthwhile to investigate the use of temporary files that store the context of the commands between run.

**Comment by pjz** [comment]
Additionally/alternatively, how about adding a `--prompt <promptname>` which will add the current query to the specified prompt. And/or have it pay attention to a `SHELLCRAFT_PROMPT=promptname` environment variable.  Add a `shell-craft reset-prompt <promptname>` subcommand to clear it the specified prompt so it doesn't hang around forever - some way to list prompts would be good too.

**Comment by JohnnyIrvin** [comment]
@pjz Will consider this!

**Comment by JohnnyIrvin** [comment]
> Additionally/alternatively, how about adding a `--prompt <promptname>` which will add the current query to the specified prompt. And/or have it pay attention to a `SHELLCRAFT_PROMPT=promptname` environment variable. Add a `shell-craft reset-prompt <promptname>` subcommand to clear it the specified prompt so it doesn't hang around forever - some way to list prompts would be good too.

Prompts are current listed via --help -- We should probably add a second ticket that allows us to add custom prompts. (I'd have to go through the tickets to see if that already exists or not)

I've just implemented this starting with bash and powershell support. We can add additional support later. The implementation I have also doesn't "remember" the conversation -- it just allows interactive execution.

**Comment by JohnnyIrvin** [comment]
Here is custom prompts ticket https://github.com/JohnnyIrvin/shell-craft/issues/69
